openapi: 3.0.0
info:
  title: WorkSpace Role Management API
  description: API to delete roles from the WorkSpace platform.
  version: 1.0.0
servers:
  - url: http://localhost:3018
    description: Local server
paths:
  /delete-role/{roleId}:
    delete:
      summary: Delete a role
      description: Endpoint to delete a role by its ID.
      operationId: deleteRole
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the role to be deleted.
      responses:
        "200":
          description: Role deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Rol eliminado exitosamente"
        "400":
          description: Invalid request.
        "500":
          description: Server error while deleting the role.
components:
  schemas:
    DeleteRoleRequest:
      type: object
      properties:
        roleId:
          type: integer
          example: 1
    DeleteRoleResponse:
      type: object
      properties:
        message:
          type: string
          example: "Rol eliminado exitosamente"
