openapi: 3.0.0
info:
  title: WorkSpace Role Update SOAP API
  description: SOAP-based API for updating roles in the WorkSpace platform.
  version: 1.0.0
servers:
  - url: http://localhost:3019
    description: Local server
paths:
  /update-role:
    post:
      summary: Update a role
      description: Update an existing role in the system using SOAP.
      operationId: updateRole
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                role:
                  type: string
                  example: "Editor"
                id:
                  type: integer
                  example: 3
      responses:
        "200":
          description: Role successfully updated.
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Rol actualizado correctamente"
        "400":
          description: Bad request, missing parameters.
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Error: id y role son requeridos"
        "404":
          description: Role not found.
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Error: no se encontró un rol con ese id"
        "500":
          description: Server error when updating the role.
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Error al actualizar el rol: Database error message"
