openapi: 3.0.0
info:
  title: User Creation API
  description: API for creating users
  version: 1.0.0
paths:
  /create:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: User created successfully
        '500':
          description: Internal server error
