openapi: 3.0.0
info:
  title: WorkSpace Role Management API
  description: API to list roles from the WorkSpace platform.
  version: 1.0.0
servers:
  - url: http://localhost:3020
    description: Local server
paths:
  /list-role:
    get:
      summary: Get all roles
      description: Retrieve a list of all roles in the system.
      operationId: listRoles
      responses:
        "200":
          description: A list of roles was successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        nombre:
                          type: string
                          example: "Admin"
        "500":
          description: Server error while retrieving roles.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al obtener los roles"
