openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API para manejar la autenticaci칩n
paths:
  /api/login:
    post:
      summary: Iniciar sesi칩n
      description: Autentica un usuario y devuelve un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
        '401':
          description: Credenciales inv치lidas
        '400':
          description: Faltan par치metros
servers:
  - url: http://localhost:3002
    description: Servidor local
