openapi: 3.0.0
info:
  title: Comment Management API
  description: API for managing comments.
  version: 1.0.0
servers:
  - url: http://localhost:3016
paths:
  /create-comments:
    post:
      summary: "Create a new comment"
      description: "Create a new comment by providing the name and the comment content."
      operationId: "createComment"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Name of the person who makes the comment"
                  example: "Jane Doe"
                comment:
                  type: string
                  description: "The content of the comment"
                  example: "This is my new comment."
      responses:
        201:
          description: "Comment created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Jane Doe"
                  comment:
                    type: string
                    example: "This is my new comment."
        400:
          description: "Bad Request, missing name or comment"
        500:
          description: "Internal Server Error"
