name: Build, Push, and Deploy Elimination Spaces

on:
  push:
    branches: [ "qa" ]
    paths:
      - "SPACE-MANAGEMENT/Elimination-Space/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/elimination-space:latest ./SPACE-MANAGEMENT/Elimination-Space/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/elimination-space:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTSPACES }} << 'EOF'
        # 1) Actualizar el sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Generar el archivo .env en el servidor EC2
        echo "DB_HOST=${{ secrets.DB_HOSTSPACE }}" > .env
        echo "DB_USER=${{ secrets.DB_USERSPACE }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSPACE }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAMESPACE }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORTSPACE }}" >> .env

        # 3) Detener y eliminar contenedor previo
        sudo docker stop elimination-space-container || true
        sudo docker rm elimination-space-container || true

        # 4) Descargar la nueva imagen desde Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elimination-space:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file .env -p 3006:3006 --name elimination-space-container ${{ secrets.DOCKERHUB_USERNAME }}/elimination-space:latest

        # 6) Limpiar imágenes antiguas para ahorrar espacio
        sudo docker image prune -f
        EOF
