name: CI/CD Pipeline

on:
  push:
    branches:
      - qa

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Authenticate DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 1: Detect changes to microservices folders
      - name: Detect changed microservices
        id: changes
        run: |
          # Validate the previous commit
          if [ -z "${{ github.event.before }}" ] || ! git cat-file -e ${{ github.event.before }} 2>/dev/null; then
            echo "No previous commit found or invalid SHA. Skipping detection."
            echo "changed_services=" >> $GITHUB_ENV
            exit 0
          fi

          # Detect changes
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          CHANGED_SERVICES=()
          for dir in */; do
            if [ -d "$dir" ]; then
              # Recorrer las subcarpetas dentro de cada carpeta de primer nivel
              for service in "$dir"*/; do
                if echo "$CHANGED_FILES" | grep -q "$service"; then
                  CHANGED_SERVICES+=("$service")
                fi
              done
            fi
          done

          # Output changed services to environment variable
          if [ ${#CHANGED_SERVICES[@]} -eq 0 ]; then
            echo "No microservices changed."
            echo "changed_services=" >> $GITHUB_ENV
          else
            echo "Modified services: ${CHANGED_SERVICES[@]}"
            echo "changed_services=${CHANGED_SERVICES[*]}" >> $GITHUB_ENV
          fi

      # Step 2: Build and Deploy changed services
      - name: Build and Deploy changed services
        run: |
          # Iterate over changed services
          for service in ${{ env.changed_services }}; do
            if [ -d "$service" ]; then
              echo "Building and deploying $service..."
              cd $service
              # Use DOCKER_USERNAME for image tagging
              IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${service}:latest"
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME
              cd - || exit
            fi
          done
