name: Build, Push, and Deploy List Availability

on:
  push:
    branches: [ "qa" ]
    paths:
      - "AVAILABILITY-MANAGEMENT/List-Availability/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/list-availability:latest ./AVAILABILITY-MANAGEMENT/List-Availability/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/list-availability:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTAVAILABILITY }} << 'EOF'
        # 1) Actualizar el sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Detener y eliminar contenedor previo
        sudo docker stop list-availability-container || true
        sudo docker rm list-availability-container || true

        # 3) Descargar la nueva imagen desde Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/list-availability:latest

        # 4) Ejecutar el contenedor pasando las variables de entorno directamente
        sudo docker run -d \
          -e DB_HOST=${{ secrets.DB_HOSTAVA }} \
          -e DB_PORT=${{ secrets.DB_PORTAVA }} \
          -e DB_USER=${{ secrets.DB_USERAVA }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSAVA }} \
          -e DB_NAME=${{ secrets.DB_NAMESAVA }} \
          -p 3008:3008 \
          --name list-availability-container ${{ secrets.DOCKERHUB_USERNAME }}/list-availability:latest

        # 5) Limpiar imágenes antiguas para ahorrar espacio
        sudo docker image prune -f
        EOF
