name: Build, Push, and Deploy Create Availability

on:
  push:
    branches: [ "qa" ]
    paths:
      - "AVAILABILITY-MANAGEMENT/Create-Availabilty/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest ./AVAILABILITY-MANAGEMENT/Create-Availabilty/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOSTAVAILABILITY }} << 'EOF'
        set -e  # Detener script si hay errores

        # 1) Actualizar el sistema e instalar Docker si no está presente
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Generar el archivo .env en /home/ec2-user/.env
        echo "DB_HOST=${{ secrets.DB_HOSTAVA }}" > /home/ec2-user/.env
        echo "DB_USER=${{ secrets.DB_USERAVA }}" >> /home/ec2-user/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSAVA }}" >> /home/ec2-user/.env
        echo "DB_NAME=${{ secrets.DB_NAMESAVA }}" >> /home/ec2-user/.env
        echo "DB_PORT=${{ secrets.DB_PORTAVA }}" >> /home/ec2-user/.env

        # Asegurar permisos correctos para .env
        chmod 600 /home/ec2-user/.env

        # Verificar contenido del archivo .env
        cat /home/ec2-user/.env

        # 3) Detener y eliminar contenedor previo si existe
        sudo docker stop create-availability-container || true
        sudo docker rm create-availability-container || true

        # 4) Descargar la nueva imagen desde Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file /home/ec2-user/.env -p 3007:3007 --name create-availability-container ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest

        # 6) Limpiar imágenes antiguas para ahorrar espacio
        sudo docker image prune -f
        EOF
