name: Build and Push Docker Images in Create-Availability

on:
  push:
    branches: [ "qa" ]
    paths:
      - "AVAILABILITY-MANAGEMENT/Create-Availabilty/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        # Construir la imagen Docker
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest .
        
        # Push de la imagen a Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
