name: Build, Push, and Deploy ListComments

on:
  push:
    branches: [ "qa" ]
    paths:
      - "COMMENT-MANAGEMENT/List-Comment/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAMEKE }}
        password: ${{ secrets.DOCKERHUB_TOKENKE }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAMEKE }}/list-comments:latest ./COMMENT-MANAGEMENT/List-Comment/
        docker push ${{ secrets.DOCKERHUB_USERNAMEKE }}/list-comments:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEYKE }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.AWS_EC2_HOSTCOMMENTS }} << 'EOF'
        # 1) Actualizar el sistema e instalar Docker si no está presente
        sudo apt update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker no encontrado, instalando..."
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

        # 2) Generar el archivo .env en el servidor EC2
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRETUSER }}" >> .env
        echo "FRONTEND_URL=${{ secrets.FRONTEND_URLUSER }}" >> .env

        # 3) Detener y eliminar contenedor previo
        sudo docker stop list-comments-container || true
        sudo docker rm list-comments-container || true

        # 4) Descargar la nueva imagen desde Docker Hub
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAMEKE }}/list-comments:latest

        # 5) Ejecutar el contenedor con el .env
        sudo docker run -d --env-file .env -p 3016:3016 --name list-comments-container ${{ secrets.DOCKERHUB_USERNAMEKE }}/list-comments:latest

        # 6) Limpiar imágenes antiguas para ahorrar espacio
        sudo docker image prune -f
        EOF
