name: Build, Push, and Deploy Create-Availability

on:
  push:
    branches: [ "qa" ]
    paths:
      - "AVAILABILITY-MANAGEMENT/Create-Availabilty/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest ./AVAILABILITY-MANAGEMENT/Create-Availabilty/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Update system and install Docker if not present
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
        # Update the system
        sudo yum update -y

        # Check if Docker is installed
        if ! command -v docker &> /dev/null
        then
          echo "Docker not found, installing..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        else
          echo "Docker is already installed."
        fi

        # Ensure Docker is running
        sudo systemctl start docker
        sudo systemctl enable docker
        EOF

    - name: Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
        sudo docker stop create-availability-container || true
        sudo docker rm create-availability-container || true
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
        sudo docker run -d -p 3007:3007 --name create-availability-container ${{ secrets.DOCKERHUB_USERNAME }}/create-availability:latest
        sudo docker image prune -f
        EOF
